# Generated by Django 5.1.4 on 2025-01-24 06:31

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_actor_genre_play_performance_reservation_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.models.play_image_path
            ),
        ),
    ]
